/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Questions.ListeQuestions;
import Questions.Question;
import Questions.Theme;
import Questions.Type.QCM;
import Questions.Type.RC;

/**
 *
 * @author lilian
 */
public class CreationQST_qcm extends javax.swing.JFrame {
    private final String qst;
    private final Theme theme;
    private final int difficulte;

    public CreationQST_qcm(String q, Theme t, int d) {
        qst = q;
        theme = t;
        difficulte = d;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grp_reponses = new javax.swing.ButtonGroup();
        lbl_reponses = new javax.swing.JLabel();
        lbl_a = new javax.swing.JLabel();
        lbl_b = new javax.swing.JLabel();
        lbl_c = new javax.swing.JLabel();
        lbl_d = new javax.swing.JLabel();
        txtF_addREP1 = new javax.swing.JTextField();
        txtF_addREP2 = new javax.swing.JTextField();
        txtF_addREP3 = new javax.swing.JTextField();
        txtF_addREP4 = new javax.swing.JTextField();
        btn_ajouterQST = new javax.swing.JButton();
        lbl_error = new javax.swing.JLabel();
        btn_exit1 = new javax.swing.JButton();
        RadioButton_a = new javax.swing.JRadioButton();
        RadioButton_b = new javax.swing.JRadioButton();
        RadioButton_c = new javax.swing.JRadioButton();
        RadioButton_d = new javax.swing.JRadioButton();

        grp_reponses.add(RadioButton_a); grp_reponses.add(RadioButton_b); grp_reponses.add(RadioButton_c); grp_reponses.add(RadioButton_d);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_reponses.setText("Choisir les réponses possibles");

        lbl_a.setText("a )");

        lbl_b.setText("b )");

        lbl_c.setText("c )");

        lbl_d.setText("d )");

        txtF_addREP1.setText("une réponse...");

        txtF_addREP2.setText("une réponse...");

        txtF_addREP3.setText("une réponse...");

        txtF_addREP4.setText("une réponse...");

        btn_ajouterQST.setText("Ajouter la question");
        btn_ajouterQST.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ajouterQSTMouseClicked(evt);
            }
        });

        lbl_error.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_error.setForeground(new java.awt.Color(255, 0, 51));

        btn_exit1.setText(" X ");
        btn_exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exit1ActionPerformed(evt);
            }
        });

        RadioButton_a.setText("a est la bonne réponse");

        RadioButton_b.setText("b est la bonne réponse");

        RadioButton_c.setText("c est la bonne réponse");

        RadioButton_d.setText("d est la bonne réponse");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(lbl_reponses)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_exit1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(btn_ajouterQST))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_d, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_c, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_b, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_a, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtF_addREP2)
                                    .addComponent(txtF_addREP4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtF_addREP1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtF_addREP3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RadioButton_a)
                                    .addComponent(RadioButton_b)
                                    .addComponent(RadioButton_c)
                                    .addComponent(RadioButton_d)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(lbl_error, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lbl_reponses))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_exit1)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtF_addREP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_a)
                    .addComponent(RadioButton_a))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtF_addREP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadioButton_b)
                    .addComponent(lbl_b))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtF_addREP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadioButton_c)
                    .addComponent(lbl_c))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtF_addREP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadioButton_d)
                    .addComponent(lbl_d))
                .addGap(18, 18, 18)
                .addComponent(lbl_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_ajouterQST)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ajouterQSTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ajouterQSTMouseClicked
        int res;
        if(RadioButton_a.isSelected())
            res = 0;
        else if (RadioButton_b.isSelected())
            res = 1;
        else if (RadioButton_c.isSelected())
            res = 2;
        else if (RadioButton_d.isSelected())
            res = 3;
        else
            res = -1;
        
        if(res!=-1)
        {
            Question<QCM> qcm = new Question<>(difficulte,new QCM(qst,res,txtF_addREP1.getText(),txtF_addREP2.getText(),txtF_addREP3.getText(),txtF_addREP4.getText()));
            theme.ajouterQuestion(qcm);
            this.dispose(); 
        }
        
         
    }//GEN-LAST:event_btn_ajouterQSTMouseClicked

    private void btn_exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exit1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_exit1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioButton_a;
    private javax.swing.JRadioButton RadioButton_b;
    private javax.swing.JRadioButton RadioButton_c;
    private javax.swing.JRadioButton RadioButton_d;
    private javax.swing.JButton btn_ajouterQST;
    private javax.swing.JButton btn_exit1;
    private javax.swing.ButtonGroup grp_reponses;
    private javax.swing.JLabel lbl_a;
    private javax.swing.JLabel lbl_b;
    private javax.swing.JLabel lbl_c;
    private javax.swing.JLabel lbl_d;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JLabel lbl_reponses;
    private javax.swing.JTextField txtF_addREP1;
    private javax.swing.JTextField txtF_addREP2;
    private javax.swing.JTextField txtF_addREP3;
    private javax.swing.JTextField txtF_addREP4;
    // End of variables declaration//GEN-END:variables
}
