/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Questions.ListeQuestions;
import Questions.Theme;
import Questions.Themes;

/**
 *
 * @author lilian
 */
public class CreationQST extends javax.swing.JFrame {
    
    public CreationQST() {
        initComponents();
        
        Themes themes = Themes.instance;
        for( Theme t : themes.getThemes()) {
            if(t!=null) comboBox_theme1.addItem(t.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_difficulte = new javax.swing.JLabel();
        comboBox_niveau1 = new javax.swing.JComboBox<>();
        lbl_qst = new javax.swing.JLabel();
        txtF_addQST = new javax.swing.JTextField();
        lbl_reponses = new javax.swing.JLabel();
        btn_qcm = new javax.swing.JButton();
        btn_rc = new javax.swing.JButton();
        btn_vf = new javax.swing.JButton();
        lbl_creerSQT = new javax.swing.JLabel();
        comboBox_theme1 = new javax.swing.JComboBox<>();
        lbl_thematique = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_difficulte.setText("2 : Choisir la difficultée");

        comboBox_niveau1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Niveau 1", "Niveau 2", "Niveau 3" }));
        comboBox_niveau1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_niveau1ActionPerformed(evt);
            }
        });

        lbl_qst.setText("3 : Ecrire la question");

        txtF_addQST.setText("une question...");

        lbl_reponses.setText("4 : Type de la question et réponses");

        btn_qcm.setText("QCM");
        btn_qcm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_qcmMouseClicked(evt);
            }
        });

        btn_rc.setText("Réponse courte");
        btn_rc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_rcMouseClicked(evt);
            }
        });

        btn_vf.setText("Vrai / Faux");
        btn_vf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_vfMouseClicked(evt);
            }
        });

        lbl_creerSQT.setText("Créer une question :");

        lbl_thematique.setText("1 : choisir le thème");

        btn_exit.setText(" X ");
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_exit)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_creerSQT)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_qst)
                            .addComponent(lbl_thematique)
                            .addComponent(lbl_difficulte))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtF_addQST, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBox_theme1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBox_niveau1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(lbl_reponses))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_rc)
                                    .addComponent(btn_vf)
                                    .addComponent(btn_qcm))))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btn_exit)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(comboBox_theme1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(comboBox_niveau1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtF_addQST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_qst, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_creerSQT)
                            .addComponent(lbl_reponses))
                        .addGap(26, 26, 26)
                        .addComponent(lbl_thematique)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_difficulte))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btn_qcm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_rc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_vf)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBox_niveau1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_niveau1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBox_niveau1ActionPerformed

    private void btn_qcmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_qcmMouseClicked
        Theme t = Themes.instance.getThemeNamed((String) comboBox_theme1.getSelectedItem());
        
        CreationQST_qcm qst = new CreationQST_qcm(txtF_addQST.getText(), t, comboBox_niveau1.getSelectedIndex()+1);
        qst.setVisible(true);
    }//GEN-LAST:event_btn_qcmMouseClicked

    private void btn_rcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_rcMouseClicked
        Theme t = Themes.instance.getThemeNamed((String) comboBox_theme1.getSelectedItem());
        
        CreationQST_RC qst = new CreationQST_RC(txtF_addQST.getText(), t, comboBox_niveau1.getSelectedIndex()+1);
        qst.setVisible(true);
    }//GEN-LAST:event_btn_rcMouseClicked

    private void btn_vfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vfMouseClicked
        Theme t = Themes.instance.getThemeNamed((String) comboBox_theme1.getSelectedItem());
        
        CreationQST_VF qst = new CreationQST_VF(txtF_addQST.getText(), t, comboBox_niveau1.getSelectedIndex()+1);
        qst.setVisible(true);
    }//GEN-LAST:event_btn_vfMouseClicked

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        this.dispose();
    }//GEN-LAST:event_btn_exitMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_qcm;
    private javax.swing.JButton btn_rc;
    private javax.swing.JButton btn_vf;
    private javax.swing.JComboBox<String> comboBox_niveau1;
    private javax.swing.JComboBox<String> comboBox_theme1;
    private javax.swing.JLabel lbl_creerSQT;
    private javax.swing.JLabel lbl_difficulte;
    private javax.swing.JLabel lbl_qst;
    private javax.swing.JLabel lbl_reponses;
    private javax.swing.JLabel lbl_thematique;
    private javax.swing.JTextField txtF_addQST;
    // End of variables declaration//GEN-END:variables
}
