/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author lilian
 */
public class CreationQST_VF extends javax.swing.JFrame {
    private final String qst;
    private final String theme;
    private final int difficulte;

    public CreationQST_VF(String q, String t, int d) {
        qst = q;
        theme = t;
        difficulte = d;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_reponses = new javax.swing.JLabel();
        toggleBTN_vrai = new javax.swing.JToggleButton();
        toggleBTN_faux = new javax.swing.JToggleButton();
        btn_addQST = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_reponses.setText("Choisir la bonne réponse");

        toggleBTN_vrai.setText("VRAI");
        toggleBTN_vrai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toggleBTN_vraiMouseClicked(evt);
            }
        });

        toggleBTN_faux.setText("FAUX");
        toggleBTN_faux.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toggleBTN_fauxMouseClicked(evt);
            }
        });

        btn_addQST.setText("Ajouter la question");
        btn_addQST.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addQSTMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_reponses)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addComponent(btn_addQST, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(96, 96, 96)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(toggleBTN_faux, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(toggleBTN_vrai, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_reponses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(toggleBTN_vrai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toggleBTN_faux)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_addQST)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toggleBTN_vraiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toggleBTN_vraiMouseClicked
        //we set the other as the opposite
        toggleBTN_faux.setSelected(false);
    }//GEN-LAST:event_toggleBTN_vraiMouseClicked

    private void toggleBTN_fauxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toggleBTN_fauxMouseClicked
        //we set the other as the opposite
        toggleBTN_vrai.setSelected(false);
    }//GEN-LAST:event_toggleBTN_fauxMouseClicked

    private void btn_addQSTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addQSTMouseClicked
        this.dispose();
    }//GEN-LAST:event_btn_addQSTMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addQST;
    private javax.swing.JLabel lbl_reponses;
    private javax.swing.JToggleButton toggleBTN_faux;
    private javax.swing.JToggleButton toggleBTN_vrai;
    // End of variables declaration//GEN-END:variables
}
