/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Joueurs.Joueur;
import Questions.Question;
import Questions.Type.RC;

/**
 *
 * @author lilian
 */
public class Jeux_RC extends javax.swing.JFrame {
    boolean qstRepondue;
    Joueur joueur;
    Question<RC> qst;
    
    public Jeux_RC() {
        joueur = new Joueur( "Billy");
        qst = new Question<>(1, new RC("Quelle est la couleur du cheval blanc d'henri 4 ?", "Blanc"));
        initComponents();
        lbl_question.setText("Question : " + qst.getEnonce().getEnonce());
        qstRepondue = false;
        btn_suivant.setVisible(false);
        btn_valider.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_phase = new javax.swing.JLabel();
        lbl_joueur = new javax.swing.JLabel();
        lbl_question = new javax.swing.JLabel();
        lbl_score = new javax.swing.JLabel();
        lbl_theme = new javax.swing.JLabel();
        txtF_reponse = new javax.swing.JTextField();
        btn_valider = new javax.swing.JButton();
        btn_suivant = new javax.swing.JButton();
        lbl_error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_phase.setText("Phase :");

        lbl_joueur.setText("Tour du joueur :");

        lbl_question.setText("Question :");

        lbl_score.setText("Score actuel :");

        lbl_theme.setText("Thème  de la question :");

        txtF_reponse.setText("Votre réponse");

        btn_valider.setText("Valider la réponse");
        btn_valider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_validerMouseClicked(evt);
            }
        });

        btn_suivant.setText("Joueur suivant");
        btn_suivant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_suivantMouseClicked(evt);
            }
        });

        lbl_error.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(txtF_reponse, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_joueur)
                            .addComponent(lbl_question)
                            .addComponent(lbl_phase))
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_theme)
                            .addComponent(lbl_score))))
                .addContainerGap(185, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_error, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btn_valider, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_suivant, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_phase)
                    .addComponent(lbl_score))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_joueur)
                    .addComponent(lbl_theme))
                .addGap(18, 18, 18)
                .addComponent(lbl_question)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(txtF_reponse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_valider)
                    .addComponent(btn_suivant)
                    .addComponent(lbl_error, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_validerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_validerMouseClicked
        if(!qstRepondue){
            
            if(!"Votre réponse".equals(txtF_reponse.getText()) && !"".equals(txtF_reponse.getText())){
                if (joueur.saisir(qst, txtF_reponse.getText())) lbl_error.setText("Bonne réponse !");
                else lbl_error.setText("Mauvaise réponse !");
                qstRepondue = true;                
                btn_suivant.setVisible(true);
                btn_valider.setVisible(false);
            }
            else {
                lbl_error.setText("Veuillez saisir une réponse");
            }
        }

    }//GEN-LAST:event_btn_validerMouseClicked

    private void btn_suivantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_suivantMouseClicked
        if(true){
            Jeux_QCM qcm = new Jeux_QCM();
            qcm.setVisible(true);
        }
        else if(false){
            Jeux_RC rc = new Jeux_RC();
            rc.setVisible(true);
        }
        else {
            Jeux_VF vf = new Jeux_VF();
            vf.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btn_suivantMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jeux_RC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jeux_RC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jeux_RC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jeux_RC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jeux_RC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_suivant;
    private javax.swing.JButton btn_valider;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JLabel lbl_joueur;
    private javax.swing.JLabel lbl_phase;
    private javax.swing.JLabel lbl_question;
    private javax.swing.JLabel lbl_score;
    private javax.swing.JLabel lbl_theme;
    private javax.swing.JTextField txtF_reponse;
    // End of variables declaration//GEN-END:variables
}
