/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Joueurs.EnsJoueurs;
import Joueurs.Joueur;
import Phases.Timer;
import Questions.Question;
import Questions.Type.QCM;
import Questions.Type.VF;
import javax.swing.table.DefaultTableModel;

public class Jeux_VF extends javax.swing.JFrame {
    Joueur joueur;
    boolean qstRepondue;
    Question<VF> qst;
    String correctReponse;
    int points;
    Timer time;
    DefaultTableModel modelJoueurs;
    MenuJeu m;

    /**
     * Creates new form Jeux_VF
     */
    public Jeux_VF(Joueur joueur, Question<?> qst, int points,MenuJeu m) {
        this.joueur = joueur;
        this.qst = (Question<VF>) qst;
        this.points = points;
        this.m=m;
        
        initComponents();
        
        StringWrapper enonce = new StringWrapper();
        StringWrapper reponse = new StringWrapper();
        
        this.qst.afficher(new StringWrapper(),new StringWrapper(),enonce,new StringWrapper(),new StringWrapper(),new StringWrapper(),new StringWrapper(),reponse);
        lbl_question.setText(enonce.getText());
        this.correctReponse = reponse.getText();
        qstRepondue = false;
        btn_suivant.setVisible(false);
        btn_valider.setVisible(true);
        
        time = new Timer(lbl_timer);
        Thread thread = new Thread(time);
        thread.start();
    }

    public Jeux_VF() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reponse = new javax.swing.ButtonGroup();
        lbl_question = new javax.swing.JLabel();
        btn_valider = new javax.swing.JButton();
        btn_suivant = new javax.swing.JButton();
        lbl_error = new javax.swing.JLabel();
        lbl_timer = new javax.swing.JLabel();
        toggleBTN_vrai = new javax.swing.JRadioButton();
        toggleBTN_faux = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_question.setText("Question :");

        btn_valider.setText("Valider la réponse");
        btn_valider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_validerMouseClicked(evt);
            }
        });

        btn_suivant.setText("Joueur suivant");
        btn_suivant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_suivantMouseClicked(evt);
            }
        });

        lbl_error.setForeground(new java.awt.Color(255, 0, 51));

        lbl_timer.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        lbl_timer.setText("Timer");

        reponse.add(toggleBTN_vrai);
        toggleBTN_vrai.setText("VRAI");

        reponse.add(toggleBTN_faux);
        toggleBTN_faux.setText("FAUX");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_question)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 359, Short.MAX_VALUE)
                        .addComponent(lbl_timer))
                    .addComponent(lbl_error, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(btn_valider, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_suivant, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(toggleBTN_vrai)
                        .addGap(18, 18, 18)
                        .addComponent(toggleBTN_faux)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbl_timer)
                .addGap(52, 52, 52)
                .addComponent(lbl_question)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toggleBTN_vrai)
                    .addComponent(toggleBTN_faux))
                .addGap(31, 31, 31)
                .addComponent(lbl_error, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_valider)
                    .addComponent(btn_suivant))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_validerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_validerMouseClicked
        if(!qstRepondue){
            if(!((toggleBTN_vrai.isSelected() == true && toggleBTN_faux.isSelected() == true) || (toggleBTN_vrai.isSelected() == false && toggleBTN_faux.isSelected() == false))){
                boolean resultat;
                if(toggleBTN_vrai.isSelected())
                    resultat = true;
                else
                    resultat = false;
                
                time.stopTimer();
                joueur.addTime(time.getTime());
                boolean X = joueur.saisir(qst, resultat);
                if (qst.getEnonce().getAnswer() == resultat){
                    lbl_error.setText("Bonne réponse !");
                    joueur.majScore(this.points);
                }
                else lbl_error.setText("Mauvaise réponse! Correct: " + this.correctReponse);
                qstRepondue = true;
                btn_suivant.setVisible(true);
                btn_valider.setVisible(false);
                
                m.reload();
                EnsJoueurs.instance.updateJoueur(joueur);
            }
            else {
                lbl_error.setText("Veuillez séléctionner une réponse");
            }
        }
    }//GEN-LAST:event_btn_validerMouseClicked

    private void btn_suivantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_suivantMouseClicked
        this.dispose();
    }//GEN-LAST:event_btn_suivantMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_suivant;
    private javax.swing.JButton btn_valider;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JLabel lbl_question;
    private javax.swing.JLabel lbl_timer;
    private javax.swing.ButtonGroup reponse;
    private javax.swing.JRadioButton toggleBTN_faux;
    private javax.swing.JRadioButton toggleBTN_vrai;
    // End of variables declaration//GEN-END:variables
}
