/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Joueurs.Joueur;
import Questions.Question;
import Questions.Type.VF;

/**
 *
 * @author lilian
 */
public class Jeux_VF extends javax.swing.JFrame {
    Joueur joueur;
    boolean qstRepondue;
    Question<VF> qst;

    /**
     * Creates new form Jeux_VF
     */
    public Jeux_VF() {
        joueur = new Joueur( "Billy");
        qst = new Question<>(3,new VF("vraiment?", true));
        qstRepondue = false;
        initComponents();
        lbl_question.setText("Question : " + qst.getEnonce().getEnonce());
        
        btn_suivant.setVisible(false);
        btn_valider.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_score = new javax.swing.JLabel();
        lbl_theme = new javax.swing.JLabel();
        lbl_question = new javax.swing.JLabel();
        lbl_phase = new javax.swing.JLabel();
        lbl_joueur = new javax.swing.JLabel();
        toggleBTN_vrai = new javax.swing.JToggleButton();
        toggleBTN_faux = new javax.swing.JToggleButton();
        btn_valider = new javax.swing.JButton();
        btn_suivant = new javax.swing.JButton();
        lbl_error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_score.setText("Score actuel :");

        lbl_theme.setText("Thème  de la question :");

        lbl_question.setText("Question :");

        lbl_phase.setText("Phase :");

        lbl_joueur.setText("Tour du joueur :");

        toggleBTN_vrai.setText("VRAI");
        toggleBTN_vrai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toggleBTN_vraiMouseClicked(evt);
            }
        });

        toggleBTN_faux.setText("FAUX");
        toggleBTN_faux.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toggleBTN_fauxMouseClicked(evt);
            }
        });

        btn_valider.setText("Valider la réponse");
        btn_valider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_validerMouseClicked(evt);
            }
        });

        btn_suivant.setText("Joueur suivant");
        btn_suivant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_suivantMouseClicked(evt);
            }
        });

        lbl_error.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_joueur)
                                    .addComponent(lbl_question)
                                    .addComponent(lbl_phase))
                                .addGap(117, 117, 117)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_theme)
                                    .addComponent(lbl_score)))
                            .addComponent(lbl_error, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_valider, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_suivant, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(toggleBTN_vrai, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(toggleBTN_faux)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_phase)
                    .addComponent(lbl_score))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_joueur)
                    .addComponent(lbl_theme))
                .addGap(18, 18, 18)
                .addComponent(lbl_question)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toggleBTN_vrai)
                    .addComponent(toggleBTN_faux))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(lbl_error, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_valider)
                    .addComponent(btn_suivant))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toggleBTN_vraiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toggleBTN_vraiMouseClicked
        //we set the other as the opposite
        toggleBTN_faux.setSelected(false);
    }//GEN-LAST:event_toggleBTN_vraiMouseClicked

    private void toggleBTN_fauxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toggleBTN_fauxMouseClicked
        //we set the other as the opposite
        toggleBTN_vrai.setSelected(false);
    }//GEN-LAST:event_toggleBTN_fauxMouseClicked

    private void btn_validerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_validerMouseClicked
        if(!qstRepondue){
            if(!((toggleBTN_vrai.isSelected() == true && toggleBTN_faux.isSelected() == true) || (toggleBTN_vrai.isSelected() == false && toggleBTN_faux.isSelected() == false))){
                boolean resultat;
                if(toggleBTN_vrai.isSelected())
                    resultat = true;
                else
                    resultat = false;
                boolean X = joueur.saisir(qst, resultat);
                if (X) lbl_error.setText("Bonne réponse !");
                else lbl_error.setText("Mauvaise réponse !");
                qstRepondue = true;
                btn_suivant.setVisible(true);
                btn_valider.setVisible(false);
            }
            else {
                lbl_error.setText("Veuillez séléctionner une réponse");
            }
        }
    }//GEN-LAST:event_btn_validerMouseClicked

    private void btn_suivantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_suivantMouseClicked
        if(true){
            Jeux_QCM qcm = new Jeux_QCM();
            qcm.setVisible(true);
        }
        else if(false){
            Jeux_RC rc = new Jeux_RC();
            rc.setVisible(true);
        }
        else {
            Jeux_VF vf = new Jeux_VF();
            vf.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btn_suivantMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jeux_VF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jeux_VF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jeux_VF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jeux_VF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jeux_VF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_suivant;
    private javax.swing.JButton btn_valider;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JLabel lbl_joueur;
    private javax.swing.JLabel lbl_phase;
    private javax.swing.JLabel lbl_question;
    private javax.swing.JLabel lbl_score;
    private javax.swing.JLabel lbl_theme;
    private javax.swing.JToggleButton toggleBTN_faux;
    private javax.swing.JToggleButton toggleBTN_vrai;
    // End of variables declaration//GEN-END:variables
}
