/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author lilian
 */
public class Jeux_VF extends javax.swing.JFrame {

    /**
     * Creates new form Jeux_VF
     */
    public Jeux_VF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_score = new javax.swing.JLabel();
        lbl_theme = new javax.swing.JLabel();
        lbl_question = new javax.swing.JLabel();
        lbl_phase = new javax.swing.JLabel();
        lbl_joueur = new javax.swing.JLabel();
        toggleBTN_vrai = new javax.swing.JToggleButton();
        toggleBTN_faux = new javax.swing.JToggleButton();
        btn_suivant = new javax.swing.JButton();
        btn_valider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_score.setText("Score actuel :");

        lbl_theme.setText("Thème  de la question :");

        lbl_question.setText("Question :");

        lbl_phase.setText("Phase :");

        lbl_joueur.setText("Tour du joueur :");

        toggleBTN_vrai.setText("VRAI");
        toggleBTN_vrai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toggleBTN_vraiMouseClicked(evt);
            }
        });

        toggleBTN_faux.setText("FAUX");
        toggleBTN_faux.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toggleBTN_fauxMouseClicked(evt);
            }
        });

        btn_suivant.setText("Joueur suivant");
        btn_suivant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_suivantMouseClicked(evt);
            }
        });

        btn_valider.setText("Valider la réponse");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_joueur)
                            .addComponent(lbl_question)
                            .addComponent(lbl_phase))
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_theme)
                            .addComponent(lbl_score)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(toggleBTN_vrai, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(toggleBTN_faux)))
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_valider, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_suivant, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_phase)
                    .addComponent(lbl_score))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_joueur)
                    .addComponent(lbl_theme))
                .addGap(18, 18, 18)
                .addComponent(lbl_question)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toggleBTN_vrai)
                    .addComponent(toggleBTN_faux))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_valider)
                    .addComponent(btn_suivant))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toggleBTN_vraiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toggleBTN_vraiMouseClicked
        //we set the other as the opposite
        toggleBTN_faux.setSelected(false);
    }//GEN-LAST:event_toggleBTN_vraiMouseClicked

    private void toggleBTN_fauxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toggleBTN_fauxMouseClicked
        //we set the other as the opposite
        toggleBTN_vrai.setSelected(false);
    }//GEN-LAST:event_toggleBTN_fauxMouseClicked

    private void btn_suivantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_suivantMouseClicked
        
    }//GEN-LAST:event_btn_suivantMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jeux_VF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jeux_VF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jeux_VF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jeux_VF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jeux_VF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_suivant;
    private javax.swing.JButton btn_valider;
    private javax.swing.JLabel lbl_joueur;
    private javax.swing.JLabel lbl_phase;
    private javax.swing.JLabel lbl_question;
    private javax.swing.JLabel lbl_score;
    private javax.swing.JLabel lbl_theme;
    private javax.swing.JToggleButton toggleBTN_faux;
    private javax.swing.JToggleButton toggleBTN_vrai;
    // End of variables declaration//GEN-END:variables
}
