/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Joueurs.EnsJoueurs;

/**
 *
 * @author lilian
 */
public class Jeux_QCM extends javax.swing.JFrame {

    /**
     * Creates new form Jeux
     */
    public Jeux_QCM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_valider = new javax.swing.JButton();
        btn_suivant = new javax.swing.JButton();
        checkBox_repA = new javax.swing.JCheckBox();
        checkBox_repC = new javax.swing.JCheckBox();
        checkBox_repD = new javax.swing.JCheckBox();
        checkBox_repB = new javax.swing.JCheckBox();
        lbl_a = new javax.swing.JLabel();
        lbl_b = new javax.swing.JLabel();
        lbl_c = new javax.swing.JLabel();
        lbl_d = new javax.swing.JLabel();
        lbl_theme = new javax.swing.JLabel();
        lbl_phase = new javax.swing.JLabel();
        lbl_joueur = new javax.swing.JLabel();
        lbl_question = new javax.swing.JLabel();
        lbl_score = new javax.swing.JLabel();
        lbl_rep1 = new javax.swing.JLabel();
        lbl_rep2 = new javax.swing.JLabel();
        lbl_rep4 = new javax.swing.JLabel();
        lbl_rep3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_valider.setText("Valider la réponse");

        btn_suivant.setText("Joueur suivant");
        btn_suivant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_suivantMouseClicked(evt);
            }
        });

        checkBox_repA.setText("a est la bonne réponse");
        checkBox_repA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkBox_repAMouseClicked(evt);
            }
        });

        checkBox_repC.setText("c est la bonne réponse");
        checkBox_repC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkBox_repCMouseClicked(evt);
            }
        });

        checkBox_repD.setText("d est la bonne réponse");
        checkBox_repD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkBox_repDMouseClicked(evt);
            }
        });

        checkBox_repB.setText("b est la bonne réponse");
        checkBox_repB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkBox_repBMouseClicked(evt);
            }
        });

        lbl_a.setText("a )");

        lbl_b.setText("b )");

        lbl_c.setText("c )");

        lbl_d.setText("d )");

        lbl_theme.setText("Thème  de la question :");

        lbl_phase.setText("Phase :");

        lbl_joueur.setText("Tour du joueur :");

        lbl_question.setText("Question :");

        lbl_score.setText("Score actuel :");

        lbl_rep1.setText("Rep1");

        lbl_rep2.setText("Rep2");

        lbl_rep4.setText("Rep4");

        lbl_rep3.setText("Rep3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_joueur)
                            .addComponent(lbl_question)
                            .addComponent(lbl_phase))
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_theme)
                            .addComponent(lbl_score)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_d, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_c, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_b, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_a, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_rep1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_rep2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_rep4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_rep3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(checkBox_repC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkBox_repB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkBox_repA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkBox_repD, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(133, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_valider, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_suivant, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_phase)
                    .addComponent(lbl_score))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_joueur)
                    .addComponent(lbl_theme))
                .addGap(18, 18, 18)
                .addComponent(lbl_question)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_b)
                            .addComponent(lbl_rep2)
                            .addComponent(checkBox_repB))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_c)
                            .addComponent(lbl_rep3)
                            .addComponent(checkBox_repC))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_d)
                            .addComponent(lbl_rep4)
                            .addComponent(checkBox_repD)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkBox_repA)
                            .addComponent(lbl_a)
                            .addComponent(lbl_rep1))
                        .addGap(92, 92, 92)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_valider)
                    .addComponent(btn_suivant))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBox_repAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBox_repAMouseClicked
        checkBox_repB.setSelected(false);
        checkBox_repC.setSelected(false);
        checkBox_repD.setSelected(false);
    }//GEN-LAST:event_checkBox_repAMouseClicked

    private void checkBox_repCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBox_repCMouseClicked
        checkBox_repA.setSelected(false);
        checkBox_repB.setSelected(false);
        checkBox_repD.setSelected(false);
    }//GEN-LAST:event_checkBox_repCMouseClicked

    private void checkBox_repDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBox_repDMouseClicked
        checkBox_repA.setSelected(false);
        checkBox_repB.setSelected(false);
        checkBox_repC.setSelected(false);
    }//GEN-LAST:event_checkBox_repDMouseClicked

    private void checkBox_repBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBox_repBMouseClicked
        checkBox_repA.setSelected(false);
        checkBox_repC.setSelected(false);
        checkBox_repD.setSelected(false);
    }//GEN-LAST:event_checkBox_repBMouseClicked

    private void btn_suivantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_suivantMouseClicked
        
    }//GEN-LAST:event_btn_suivantMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jeux_QCM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jeux_QCM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jeux_QCM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jeux_QCM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jeux_QCM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_suivant;
    private javax.swing.JButton btn_valider;
    private javax.swing.JCheckBox checkBox_repA;
    private javax.swing.JCheckBox checkBox_repB;
    private javax.swing.JCheckBox checkBox_repC;
    private javax.swing.JCheckBox checkBox_repD;
    private javax.swing.JLabel lbl_a;
    private javax.swing.JLabel lbl_b;
    private javax.swing.JLabel lbl_c;
    private javax.swing.JLabel lbl_d;
    private javax.swing.JLabel lbl_joueur;
    private javax.swing.JLabel lbl_phase;
    private javax.swing.JLabel lbl_question;
    private javax.swing.JLabel lbl_rep1;
    private javax.swing.JLabel lbl_rep2;
    private javax.swing.JLabel lbl_rep3;
    private javax.swing.JLabel lbl_rep4;
    private javax.swing.JLabel lbl_score;
    private javax.swing.JLabel lbl_theme;
    // End of variables declaration//GEN-END:variables
}
