/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author lilian
 */
public class Lancement extends javax.swing.JFrame {

    /**
     * Creates new form Lancement
     */
    public Lancement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nbJoueur = new javax.swing.JLabel();
        lbl_theme = new javax.swing.JLabel();
        comboBox_nbJoueur = new javax.swing.JComboBox<>();
        comboBox_theme = new javax.swing.JComboBox<>();
        comboBox_niveau = new javax.swing.JComboBox<>();
        lbl_niveau = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_questions = new javax.swing.JTable();
        lbl_creerSQT = new javax.swing.JLabel();
        comboBox_theme1 = new javax.swing.JComboBox<>();
        lbl_thematique = new javax.swing.JLabel();
        lbl_difficulte = new javax.swing.JLabel();
        comboBox_niveau1 = new javax.swing.JComboBox<>();
        lbl_qst = new javax.swing.JLabel();
        txtF_addQST = new javax.swing.JTextField();
        lbl_reponses = new javax.swing.JLabel();
        lbl_a = new javax.swing.JLabel();
        lbl_b = new javax.swing.JLabel();
        lbl_c = new javax.swing.JLabel();
        lbl_d = new javax.swing.JLabel();
        txtF_addREP1 = new javax.swing.JTextField();
        txtF_addREP2 = new javax.swing.JTextField();
        txtF_addREP3 = new javax.swing.JTextField();
        txtF_addREP4 = new javax.swing.JTextField();
        checkBox_repA = new javax.swing.JCheckBox();
        checkBox_repC = new javax.swing.JCheckBox();
        checkBox_repD = new javax.swing.JCheckBox();
        checkBox_repB = new javax.swing.JCheckBox();
        btn_ajouterQST = new javax.swing.JButton();
        btn_jeu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_nbJoueur.setText("Nombre de joueur");

        lbl_theme.setText("Thème de la question :");

        comboBox_nbJoueur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4 joueurs", "5 joueurs", "6 joueurs", "7 joueurs", "8 joueurs", "9 joueurs", "10 joueurs", "11 joueurs", "12 joueurs", "13 joueurs", "14 joueurs", "15 joueurs", "16 joueurs", "17 joueurs", "18 joueurs", "19 joueurs", "20 joueurs" }));

        comboBox_theme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personnages importants", "Technologie", "Sport", "Géographie", "Culture générale", "Dates", "Internet", "Géopolitique", "Logique", "Thème surprise" }));

        comboBox_niveau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Niveau 1", "Niveau 2", "Niveau 3" }));

        lbl_niveau.setText("Niveau :");

        table_questions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Question", "Réponse 1", "Réponse 2", "Réponse 3", "Réponse 4", "Solution"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_questions);

        lbl_creerSQT.setText("Créer une question :");

        comboBox_theme1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personnages importants", "Technologie", "Sport", "Géographie", "Culture générale", "Dates", "Internet", "Géopolitique", "Logique", "Thème surprise" }));

        lbl_thematique.setText("1 : choisir le thème");

        lbl_difficulte.setText("2 : Choisir la difficultée");

        comboBox_niveau1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Niveau 1", "Niveau 2", "Niveau 3" }));
        comboBox_niveau1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_niveau1ActionPerformed(evt);
            }
        });

        lbl_qst.setText("3 : Ecrire la question");

        txtF_addQST.setText("une question...");

        lbl_reponses.setText("4 : Réponses possibles");

        lbl_a.setText("a )");

        lbl_b.setText("b )");

        lbl_c.setText("c )");

        lbl_d.setText("d )");

        txtF_addREP1.setText("une réponse...");

        txtF_addREP2.setText("une réponse...");
        txtF_addREP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtF_addREP2ActionPerformed(evt);
            }
        });

        txtF_addREP3.setText("une réponse...");

        txtF_addREP4.setText("une réponse...");
        txtF_addREP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtF_addREP4ActionPerformed(evt);
            }
        });

        checkBox_repA.setText("a est la bonne réponse");

        checkBox_repC.setText("c est la bonne réponse");

        checkBox_repD.setText("d est la bonne réponse");
        checkBox_repD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_repDActionPerformed(evt);
            }
        });

        checkBox_repB.setText("b est la bonne réponse");
        checkBox_repB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_repBActionPerformed(evt);
            }
        });

        btn_ajouterQST.setText("Ajouter la question");

        btn_jeu.setText("Commencer le jeu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_qst)
                                    .addComponent(lbl_thematique)
                                    .addComponent(lbl_difficulte))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtF_addQST, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBox_theme1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBox_niveau1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_b)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtF_addREP2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbl_d, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtF_addREP4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_a)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtF_addREP1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbl_c)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtF_addREP3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(checkBox_repA, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                    .addComponent(checkBox_repC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(checkBox_repD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(checkBox_repB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addComponent(btn_ajouterQST))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_theme)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBox_theme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(lbl_niveau)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboBox_niveau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lbl_nbJoueur)
                                    .addGap(18, 18, 18)
                                    .addComponent(comboBox_nbJoueur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_jeu, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lbl_creerSQT)
                        .addGap(370, 370, 370)
                        .addComponent(lbl_reponses)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nbJoueur)
                            .addComponent(comboBox_nbJoueur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btn_jeu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_theme)
                    .addComponent(comboBox_theme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBox_niveau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_niveau))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(comboBox_theme1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(comboBox_niveau1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtF_addQST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_qst, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_creerSQT)
                            .addComponent(lbl_reponses))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(lbl_thematique)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_difficulte))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_a)
                                    .addComponent(txtF_addREP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkBox_repA)
                                    .addComponent(btn_ajouterQST))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtF_addREP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkBox_repB)
                                    .addComponent(lbl_b))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(checkBox_repC)
                                    .addComponent(txtF_addREP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_c))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(checkBox_repD)
                                    .addComponent(txtF_addREP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_d))))))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtF_addREP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtF_addREP4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtF_addREP4ActionPerformed

    private void checkBox_repDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_repDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox_repDActionPerformed

    private void checkBox_repBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_repBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox_repBActionPerformed

    private void comboBox_niveau1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_niveau1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBox_niveau1ActionPerformed

    private void txtF_addREP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtF_addREP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtF_addREP2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lancement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lancement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lancement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lancement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lancement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ajouterQST;
    private javax.swing.JButton btn_jeu;
    private javax.swing.JCheckBox checkBox_repA;
    private javax.swing.JCheckBox checkBox_repB;
    private javax.swing.JCheckBox checkBox_repC;
    private javax.swing.JCheckBox checkBox_repD;
    private javax.swing.JComboBox<String> comboBox_nbJoueur;
    private javax.swing.JComboBox<String> comboBox_niveau;
    private javax.swing.JComboBox<String> comboBox_niveau1;
    private javax.swing.JComboBox<String> comboBox_theme;
    private javax.swing.JComboBox<String> comboBox_theme1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_a;
    private javax.swing.JLabel lbl_b;
    private javax.swing.JLabel lbl_c;
    private javax.swing.JLabel lbl_creerSQT;
    private javax.swing.JLabel lbl_d;
    private javax.swing.JLabel lbl_difficulte;
    private javax.swing.JLabel lbl_nbJoueur;
    private javax.swing.JLabel lbl_niveau;
    private javax.swing.JLabel lbl_qst;
    private javax.swing.JLabel lbl_reponses;
    private javax.swing.JLabel lbl_thematique;
    private javax.swing.JLabel lbl_theme;
    private javax.swing.JTable table_questions;
    private javax.swing.JTextField txtF_addQST;
    private javax.swing.JTextField txtF_addREP1;
    private javax.swing.JTextField txtF_addREP2;
    private javax.swing.JTextField txtF_addREP3;
    private javax.swing.JTextField txtF_addREP4;
    // End of variables declaration//GEN-END:variables
}
