/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Questions.Theme;

/**
 *
 * @author lilian
 */
public class Renommer_theme extends javax.swing.JFrame {
    Theme theme;
    Lancement framePrecedente;
    
    public Renommer_theme(Theme t, Lancement l) {
        theme = t;
        framePrecedente = l;
        initComponents();
        lbl_oldName.setText("Ancien nom : " + theme.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_oldName = new javax.swing.JLabel();
        lbl_newName = new javax.swing.JLabel();
        btn_accepter = new javax.swing.JButton();
        txtF_nom = new javax.swing.JTextField();
        btn_exit1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_oldName.setText("Ancien nom :");

        lbl_newName.setText("Nouveau nom :");

        btn_accepter.setText("Accepter");
        btn_accepter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_accepterMouseClicked(evt);
            }
        });

        btn_exit1.setText(" X ");
        btn_exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exit1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Renommer un thème");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(46, 46, 46)
                        .addComponent(btn_exit1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_oldName)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbl_newName)
                            .addGap(18, 18, 18)
                            .addComponent(txtF_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_accepter)
                        .addGap(111, 111, 111))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_exit1)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(lbl_oldName)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_newName)
                    .addComponent(txtF_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btn_accepter)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_accepterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_accepterMouseClicked
        theme.modifNom(txtF_nom.getText());
        framePrecedente.dispose();
        Lancement nouv = new Lancement();
        nouv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_accepterMouseClicked

    private void btn_exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exit1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_exit1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_accepter;
    private javax.swing.JButton btn_exit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_newName;
    private javax.swing.JLabel lbl_oldName;
    private javax.swing.JTextField txtF_nom;
    // End of variables declaration//GEN-END:variables
}
